myportfolio/portfolio/myapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'myapp'

urlpatterns = [    
    path('', views.portfolio, name='portfolio'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('manage/', views.manage, name='manage'),
    path('about/add/', views.about_create, name='about_add'),
    path('about/edit/<int:pk>/', views.about_edit, name='about_edit'),
    path('skill/delete/<int:pk>/', views.delete_skill, name='delete_skill'),
    path('portfolio/delete/<int:pk>/', views.delete_project, name='delete_project'),
    path('contact/delete/<int:pk>/', views.delete_contact, name='delete_contact'),
    path('home/edit/<int:pk>/', views.home_edit, name='home_edit'),
    path('skill/edit/<int:pk>/', views.skill_edit, name='skill_edit'),
    path('social/edit/<int:pk>/', views.social_edit, name='social_edit'),
    path('profile/edit/<int:pk>/', views.cv_edit, name='cv_edit'),
    path('portfolio/edit/<int:pk>/', views.portfolio_edit, name='portfolio_edit'),
    path('add_skill/', views.add_skill, name='add_skill'),
    path('add_project/', views.add_project, name='add_project'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myportfolio/portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='myapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myportfolio/portfolio/myapp/models.py
from django.db import models

class Home(models.Model):
    image = models.ImageField(upload_to='files/')

    def __str__(self):
        return f"image {self.pk}"
    
class About(models.Model):
    aboutme = models.TextField()
    image1 = models.ImageField(upload_to='files/')
    image2 = models.ImageField(upload_to='files/')
    
    def __str__(self):
        return "About Section"
    

class Skill(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='files/')
    percentage = models.IntegerField()

    def __str__(self):
        return self.name

class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='files/')
    link = models.URLField(max_length=200)

    def __str__(self):
        return self.title

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    project_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.name} - {self.project_name}"

class Profile(models.Model):
    cv_image = models.ImageField(upload_to='files/', null=True, blank=True)
    cv_file = models.FileField(upload_to='files/', null=True, blank=True)

    def __str__(self):
        return f"Profile {self.pk}"

class Social(models.Model):
    fblink = models.URLField(max_length=200)
    instalink = models.URLField(max_length=200)
    xlink = models.URLField(max_length=200)
    tglink = models.URLField(max_length=200)

    def get_urls(self):
        # Return a dictionary of the links
        return {
            'facebook': self.fblink,
            'instagram': self.instalink,
            'x_link': self.xlink,
            'telegram': self.tglink,
        }






myportfolio/portfolio/myapp/forms.py
from django import forms
from .models import Contact, About, Home, Skill, Project, Profile, Social

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'project_name']

class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = ['aboutme', 'image1', 'image2']

class HomeForm(forms.ModelForm):
    class Meta:
        model = Home
        fields = ['image']

class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['name', 'logo', 'percentage']

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'image', 'link']

class CvForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['cv_image', 'cv_file']

class SocialForm(forms.ModelForm):
    class Meta:
        model = Social
        fields = ['fblink', 'instalink', 'xlink', 'tglink']

myportfolio/portfolio/myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Home, About, Skill, Project, Profile, Contact, Social
from .forms import ContactForm
from django.contrib.auth.decorators import login_required
from .models import About
from .forms import AboutForm, HomeForm, SkillForm, ProjectForm, CvForm, SocialForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('myapp:manage')
        else:
            # Invalid login, display an error message
            return render(request, 'login.html', {'error_message': 'Invalid username or password.'})
    else:
        return render(request, 'myapp/login.html')
    
def logout_view(request):
    logout(request)
    # Redirect to a success page or any other page after logout
    return redirect('myapp:login')  # Replace 'myapp:login' with the URL name of your login page

def portfolio(request):
    contact_form = ContactForm()
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
    profile = Profile.objects.first()  
    home_image = Home.objects.first()
    about_section = About.objects.first()  
    skills = Skill.objects.all() 
    projects = Project.objects.all()
    social_links = Social.objects.first()

    context = {
        'home_image': home_image,
        'about_section': about_section,
        'skills': skills,
        'projects':projects,
        'profile': profile,
        'contact_form': contact_form, 
        'social_links':social_links,
    }
    return render(request, 'myapp/portfolio.html', context)

@login_required(login_url='/login')
def manage(request):
    homes = Home.objects.all()
    abouts = About.objects.all()
    skills = Skill.objects.all()
    projects = Project.objects.all()
    contacts = Contact.objects.all()
    profiles = Profile.objects.all()
    socials = Social.objects.all()

    context = {
        'homes': homes,
        'abouts': abouts,
        'skills': skills,
        'projects': projects,
        'contacts': contacts,
        'profiles': profiles,
        'socials': socials,
    }
    return render(request, 'myapp/manage.html', context)

@login_required(login_url='/login')
def about_create(request):
    if request.method == "POST":
        form = AboutForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myapp:manage')
    else:
        form = AboutForm()
    return render(request, 'myapp/about.html', {'form': form})

@login_required(login_url='/login')
def about_edit(request, pk):
    item = get_object_or_404(About, pk=pk)
    if request.method == "POST":
        form = AboutForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return render(request, 'myapp/success.html')  # Render a template to close the window
    else:
        form = AboutForm(instance=item)
    return render(request, 'myapp/about.html', {'form': form})


@login_required(login_url='/login')
def home_edit(request, pk):
    item = get_object_or_404(Home, pk=pk)
    if request.method == "POST":
        form = HomeForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return render(request, 'myapp/success.html')  # Render a template to close the window
        
    else:
        form = HomeForm(instance=item)
    return render(request, 'myapp/home.html', {'form': form})

@login_required(login_url='/login')
def skill_edit(request, pk):
    item = get_object_or_404(Skill, pk=pk)
    if request.method == "POST":
        form = SkillForm(request.POST,  request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return render(request, 'myapp/success.html')  # Render a template to close the window
    else:
        form = SkillForm(instance=item)
    return render(request, 'myapp/skill.html', {'form': form})

@login_required(login_url='/login')
def portfolio_edit(request, pk):
    item = get_object_or_404(Project, pk=pk)
    if request.method == "POST":
        form = ProjectForm(request.POST,  request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return render(request, 'myapp/success.html')  # Render a template to close the window
    else:
        form = ProjectForm(instance=item)
    return render(request, 'myapp/projects.html', {'form': form})

@login_required(login_url='/login')
def delete_skill(request, pk):        
    skill = Skill.objects.get(pk=pk)
    skill.delete()

    return redirect('myapp:manage' )   

@login_required(login_url='/login')
def delete_project(request, pk):
    try:
        project = Project.objects.get(pk=pk)
    except Project.DoesNotExist:
        # Handle the case where the project doesn't exist
        # For example, you can show an error message or redirect to a different page
        return HttpResponse("Project not found", status=404)
    
    project.delete()
    return redirect('myapp:manage') 

@login_required(login_url='/login')
def delete_contact(request, pk):        
    contact = Contact.objects.get(pk=pk)
    contact.delete()

    return redirect('myapp:manage' )   

@login_required(login_url='/login')
def add_skill(request):
    if request.method == 'POST':
        form = SkillForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'myapp/success.html')  # Render a template to close the window
    else:
        form = SkillForm()
    
    return render(request, 'myapp/skill.html', {'form': form})

@login_required(login_url='/login')
def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'myapp/success.html')  # Render a template to close the window
    else:
        form = ProjectForm()
    
    return render(request, 'myapp/projects.html', {'form': form})

@login_required(login_url='/login')
def cv_edit(request, pk):
    item = get_object_or_404(Profile, pk=pk)
    if request.method == "POST":
        form = CvForm(request.POST,  request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return render(request, 'myapp/success.html')  # Render a template to close the window
    else:
        form = CvForm(instance=item)
    return render(request, 'myapp/profile.html', {'form': form})

@login_required(login_url='/login')
def social_edit(request, pk):
    item = get_object_or_404(Social, pk=pk)
    if request.method == "POST":
        form = SocialForm(request.POST,  request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return render(request, 'myapp/success.html')  # Render a template to close the window
    else:
        form = SocialForm(instance=item)
    return render(request, 'myapp/social.html', {'form': form})

myportfolio/portfolio/myapp/templates/myapp/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Edit About Details</title>
    <link rel="icon" type="image/png" href="{% static 'img/plogo.png' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
    <h2>{% if object %}Add{% else %}Edit{% endif %} About Details</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group1">
        <div class="form-group">
            <div class="form-content1">               
                <img id="imagePreview1" class="preview-image" src="{% if form.instance.image1 %}{{ form.instance.image1.url }}{% else %}{% static 'images/placeholder.jpg' %}{% endif %}" alt="Preview">
            </div>
            <div class="form-content2">
                <input type="file" id="fileInput1" name="image1" accept="image/*" onchange="previewImage(event, 'imagePreview1')" class="choose-file-button">
            </div>
        </div>
        <div class="form-group">
            <div class="form-content1">               
                <img id="imagePreview2" class="preview-image" src="{% if form.instance.image2 %}{{ form.instance.image2.url }}{% else %}{% static 'images/placeholder.jpg' %}{% endif %}" alt="Preview">
            </div>
            <div class="form-content2">
                <input type="file" id="fileInput2" name="image2" accept="image/*" onchange="previewImage(event, 'imagePreview2')" class="choose-file-button">
            </div>
        </div>
    </div>
         <div class="form-group">
            <div class="form-content">
                <textarea id="id_aboutme" name="aboutme" placeholder="Write About You">{{ form.instance.aboutme }}</textarea>
            </div>
        </div>
        <button type="submit">Save</button>
    </form>
    <script>
        // Function to preview selected image
        function previewImage(event, previewId) {
            var input = event.target;
            var preview = document.getElementById(previewId);
            var reader = new FileReader();
            
            reader.onload = function(){
                preview.src = reader.result;
            };
            
            reader.readAsDataURL(input.files[0]);
        }
    </script>
</body>
</html>

myportfolio/portfolio/myapp/templates/myapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="icon" type="image/png" href="{% static 'img/plogo.png' %}">
</head>
<body>
    <div class="login-container">
        <h1>Please Login</h1>
        <form method="post" action="{% url 'myapp:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Login</button>
        </form>
    </div>
</body>
</html>

myportfolio/portfolio/myapp/templates/myapp/manage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Dashboard</title>
    <link rel="icon" type="image/png" href="{% static 'img/plogo.png' %}">
    <link rel="stylesheet" href="{% static 'css/admin.css' %}">
</head>
<body>
    <h1>Admin Dashboard</h1>
    <form action="{% url 'myapp:logout' %}" method="post">
        {% csrf_token %}
    <section>
        <h2>Homes</h2>
        <table>
            <tr>
                <th>Image</th>
                <th>Actions</th>
            </tr>
            {% for home in homes %}
            <tr>
                <td>{{ home.image }}</td>
                <td>
                    <a href="{% url 'myapp:home_edit' pk=home.pk %}" class="edit-home" onclick="openHomeEditPage(event)">Edit</a>

                </td>
            </tr>
            {% endfor %}
        </table>
    </section>
    <section>
        <h2>Abouts</h2>
        <table>
            <tr>
                <th>About Me</th>
                <th>Image 1</th>
                <th>Image 2</th>
                <th>Actions</th>
            </tr>
            {% for about in abouts %}
            <tr>
                <td>{{ about.aboutme }}</td>
                <td>{{ about.image1 }}</td>
                <td>{{ about.image2 }}</td>
                <td>
                    <a href="{% url 'myapp:about_edit' pk=about.pk %}" class="edit-about" onclick="openAboutEditPage(event)">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </section>
    <section>
        <h2>Skills</h2>
        <table>
            <tr>
                <th>Name</th>
                <th>Logo</th>
                <th>Percentage</th>
                <th>Actions</th>
            </tr>
            {% for skill in skills %}
            <tr>
                <td>{{ skill.name }}</td>
                <td>{{ skill.logo }}</td>
                <td>{{ skill.percentage }}</td>
                <td>
                    <a href="{% url 'myapp:skill_edit' pk=skill.pk %}" class="edit-skill" onclick="openSkillEditPage(event)">Edit</a>
                    <form action="{% url 'myapp:delete_skill' skill.pk %}" method="post" id="deleteForm-{{ skill.pk }}">
                        {% csrf_token %}
                        <button type="button" class="delete-button" onclick="showDeleteConfirmation('deleteForm-{{ skill.pk }}')">Delete</button>
                    </form>                                
                </td>
            </tr>
            {% endfor %}
        </table>
        <a href="/add_skill" class="add-skill" onclick="newSkillEditPage(event)">Add Skill</a>
    </section>
    <section>
        <h2>Portfolio</h2>
        <table>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Image</th>
                <th>Link</th>
                <th>Actions</th>
            </tr>
            {% for project in projects %}
            <tr>
                <td>{{ project.title }}</td>
                <td>{{ project.description }}</td>
                <td>{{ project.image }}</td>
                <td>{{ project.link }}</td>
                <td>
                    <a href="{% url 'myapp:portfolio_edit' pk=project.pk %}" class="edit-project"  onclick="openProjectEditPage(event)">Edit</a>
                    <form action="{% url 'myapp:delete_project' project.pk %}" method="post" id="deleteForm-{{ project.pk }}">
                        {% csrf_token %}
                        <button type="button" class="delete-button" onclick="showDeleteConfirmation('deleteForm-{{ project.pk }}')">Delete</button>
                    </form>                  
                </td>
            </tr>
            {% endfor %}
        </table>
        <a href="/add_project" class="add-project"  onclick="newProjectEditPage(event)">Add Project</a>
    </section>
    <section>
        <h2>CV</h2>
        <table>
            <tr>
                <th>CV Image</th>
                <th>CV File</th>
                <th>Actions</th>
            </tr>
            {% for profile in profiles %}
            <tr>
                <td>{{ profile.cv_image }}</td>
                <td>{{ profile.cv_file }}</td>
                <td>
                    <a href="{% url 'myapp:cv_edit' pk=profile.pk %}" class="edit-profile" onclick="openProfileEditPage(event)">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </section>
    <section>
        <h2>Messages</h2>
        <table>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Project Name</th>
                <th>Actions</th>
            </tr>
            {% for contact in contacts %}
            <tr>
                <td>{{ contact.name }}</td>
                <td>{{ contact.email }}</td>
                <td>{{ contact.project_name }}</td>
                <td>
                    <form action="{% url 'myapp:delete_contact' contact.pk %}" method="post" id="deleteForm-{{ contact.pk }}">
                        {% csrf_token %}
                        <button type="button" class="delete-button" onclick="showDeleteConfirmation('deleteForm-{{ contact.pk }}')">Delete</button>
                    </form>    
                </td>
            </tr>
            {% endfor %}
        </table>
    </section>
    <section>
        <h2>Socials</h2>
        <table>
            <tr>
                <th>Platform & Link</th>
                <th>Action</th>
            </tr>
            {% for social in socials %}
            <tr>
                <td>
                    {% for platform, url in social.get_urls.items %}
                        <strong>{{ platform }}:</strong>{{ url }}</a><br>
                    {% endfor %}
                </td>
                <td>
                    <a href="{% url 'myapp:social_edit' pk=social.pk %}" class="edit-social" onclick="openSocialEditPage(event)">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </section>
    <button type="submit">Logout</button>
    </form>   
    <script>
        function showDeleteConfirmation(formId) {
            const confirmation = confirm("Are you sure you want to delete this?");
            if (confirmation) {
                document.getElementById(formId).submit();
            }
        }

        function openHomeEditPage(event) {
            event.preventDefault(); 
            var url = event.target.href; // Get the URL from the link's href attribute            
            window.open(url, '_blank', 'width=650, height=550,toolbar=no,scrollbars=no,resizable=no,max-width=600,max-height=400,min-width=600,min-height=400,background-color=red,top=' + ((window.innerHeight - 400) / 2) + ',left=' + ((window.innerWidth - 600) / 2));
        }

        function openSkillEditPage(event) {
            event.preventDefault(); 
            var url = event.target.href; // Get the URL from the link's href attribute            
            window.open(url, '_blank', 'width=650, height=450,toolbar=no,scrollbars=no,resizable=no,max-width=600,max-height=400,min-width=600,min-height=400,background-color=red,top=' + ((window.innerHeight - 400) / 2) + ',left=' + ((window.innerWidth - 600) / 2));
        }

        function newSkillEditPage(event) {
            event.preventDefault(); 
            var url = event.target.href; // Get the URL from the link's href attribute            
            window.open(url, '_blank', 'width=650, height=450,toolbar=no,scrollbars=no,resizable=no,max-width=600,max-height=400,min-width=600,min-height=400,background-color=red,top=' + ((window.innerHeight - 400) / 2) + ',left=' + ((window.innerWidth - 600) / 2));
        }
        
        function openAboutEditPage(event) {
            event.preventDefault(); 
            var url = event.target.href; // Get the URL from the link's href attribute            
            window.open(url, '_blank', 'width=650, height=550,toolbar=no,scrollbars=no,resizable=no,max-width=600,max-height=400,min-width=600,min-height=400,background-color=red,top=' + ((window.innerHeight - 400) / 2) + ',left=' + ((window.innerWidth - 600) / 2));
        }  

        function openProjectEditPage(event) {
            event.preventDefault(); 
            var url = event.target.href; // Get the URL from the link's href attribute            
            window.open(url, '_blank', 'width=650, height=650,toolbar=no,scrollbars=no,resizable=no,max-width=600,max-height=400,min-width=600,min-height=400,background-color=red,top=' + ((window.innerHeight - 400) / 2) + ',left=' + ((window.innerWidth - 600) / 2));
        }

        function newProjectEditPage(event) {
            event.preventDefault(); 
            var url = event.target.href; // Get the URL from the link's href attribute            
            window.open(url, '_blank', 'width=650, height=650,toolbar=no,scrollbars=no,resizable=no,max-width=600,max-height=400,min-width=600,min-height=400,background-color=red,top=' + ((window.innerHeight - 400) / 2) + ',left=' + ((window.innerWidth - 600) / 2));
        }

        function openProfileEditPage(event) {
            event.preventDefault(); 
            var url = event.target.href; // Get the URL from the link's href attribute            
            window.open(url, '_blank', 'width=650, height=700,toolbar=no,scrollbars=no,resizable=no,max-width=600,max-height=400,min-width=600,min-height=400,background-color=red,top=' + ((window.innerHeight - 400) / 2) + ',left=' + ((window.innerWidth - 600) / 2));
        }

        function openSocialEditPage(event) {
            event.preventDefault(); 
            var url = event.target.href; // Get the URL from the link's href attribute            
            window.open(url, '_blank', 'width=650, height=350,toolbar=no,scrollbars=no,resizable=no,max-width=600,max-height=400,min-width=600,min-height=400,background-color=red,top=' + ((window.innerHeight - 400) / 2) + ',left=' + ((window.innerWidth - 600) / 2));
        }
    </script>
</body>
</html>

myportfolio/portfolio/myapp/templates/myapp/projects.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Edit Project Details</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="icon" type="image/png" href="{% static 'img/plogo.png' %}">
</head>
<body>
    <h2>{% if object %}Add{% else %}Edit{% endif %} Project Details</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <div class="form-content4">
                <img id="imagePreview" class="preview-image" src="{% if form.instance.image %}{{ form.instance.image.url }}{% else %}{% static 'images/placeholder.jpg' %}{% endif %}" alt="Preview">
            </div>
            <div class="form-content">
                <input type="file" id="fileInput" name="image" accept="image/*" onchange="previewImage(event)" class="choose-file-button">
            </div>
        </div>
        <div class="form-group">
            <div class="form-content">
                <input type="text" id="id_title" name="title" value="{{ form.instance.title }}" placeholder="Project Title">
            </div>
        </div>
        <div class="form-group">
            <div class="form-content">
                <textarea id="id_description" name="description" rows="4" cols="50" placeholder="Project Description">{{ form.instance.description }}</textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="form-content">
                <input type="text" id="id_link" name="link" value="{{ form.instance.link }}" placeholder="Project's Link">
            </div>
        </div>
        <button type="submit">Save</button>
    </form>
    <script>
        // Function to preview selected image
        function previewImage(event) {
            var input = event.target;
            var preview = document.getElementById('imagePreview');
            var reader = new FileReader();
            
            reader.onload = function(){
                preview.src = reader.result;
            };
            
            reader.readAsDataURL(input.files[0]);
        }
    </script>
</body>
</html>

myportfolio/portfolio/myapp/templates/myapp/skill.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Edit Skill Details</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="icon" type="image/png" href="{% static 'img/plogo.png' %}">
</head>
<body>
    <h2>{% if object %}Add{% else %}Edit{% endif %} Skill Details</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <div class="form-content3">               
                <img id="imagePreview" class="preview-image" src="{% if form.instance.logo %}{{ form.instance.logo.url }}{% else %}{% static 'images/placeholder.jpg' %}{% endif %}" alt="Preview">
            </div>
            <div class="form-content">
                <input type="file" id="fileInput" name="logo" accept="image/*" onchange="previewImage(event)" class="choose-file-button">
            </div>
        </div>
        <div class="form-group">
            <div class="form-content">
                <input type="text" id="id_name" name="name" value="{{ form.instance.name }}">
            </div>
        </div>
        <div class="form-group">
            <div class="form-content">
                <input type="number" id="id_percentage" name="percentage" value="{{ form.instance.percentage }}">
            </div>
        </div>
        <button type="submit">Save</button>
    </form>
    <script>
        // Function to preview selected image
        function previewImage(event) {
            var input = event.target;
            var preview = document.getElementById('imagePreview');
            var reader = new FileReader();
            
            reader.onload = function(){
                preview.src = reader.result;
            };
            
            reader.readAsDataURL(input.files[0]);
        }
    </script>
</body>
</html>

myportfolio/portfolio/myapp/templates/myapp/social.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Edit Social Details</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="icon" type="image/png" href="{% static 'img/plogo.png' %}">
</head>
<body>
    <h2>{% if object %}Add{% else %}Edit{% endif %} Social Details</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_fblink">Facebook Link:</label>
            <div class="form-content">
                <input type="url" id="id_fblink" name="fblink" value="{{ form.instance.fblink }}">
            </div>
        </div>
        <div class="form-group">
            <label for="id_instalink">Instagram Link:</label>
            <div class="form-content">
                <input type="url" id="id_instalink" name="instalink" value="{{ form.instance.instalink }}">
            </div>
        </div>
        <div class="form-group">
            <label for="id_xlink">X Link:</label>
            <div class="form-content">
                <input type="url" id="id_xlink" name="xlink" value="{{ form.instance.xlink }}">
            </div>
        </div>
        <div class="form-group">
            <label for="id_tglink">Telegram Link:</label>
            <div class="form-content">
                <input type="url" id="id_tglink" name="tglink" value="{{ form.instance.tglink }}">
            </div>
        </div>
        <button type="submit">Save</button>
    </form>
</body>
</html>